export const ACTIONS = {
    NOTIFY: 'NOTIFY',
    LOADING: 'LOADING',
    ADD_MODAL: 'ADD_MODAL',
    AUTH: 'AUTH',
    ADD_CART: 'ADD_CART',
    SEARCH: 'SEARCH',
    GET_CONVERSATIONS: "GET_CONVERSATIONS",
    ADD_NEW_CONVERSATION: "ADD_NEW_CONVERSATION",
    ACTIVE_CHAT_USER: "ACTIVE_CHAT_USER",
    OPEN_CHAT: "OPEN_CHAT",
    NEW_ACCESS: "NEW_ACCESS"
}